name: starter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  dio: ^5.0.3
  cached_network_image: ^3.2.3

  auto_route: ^5.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0

  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.2

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.2.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
