name: khana
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_route: ^5.0.2
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_smart_retry: ^1.3.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  fresh_dio: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.2
  hydrated_notifier: ^1.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  once: ^1.4.1
  retrofit: ^3.3.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.0.3
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
